# Generated by Django 6.1.1 on 2026-09-17 19:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.CharField(max_length=512)),
                ('pickup_location', models.CharField(max_length=512)),
                ('dropoff_location', models.CharField(max_length=512)),
                ('current_cycle_used_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shift_start', models.DateTimeField()),
                ('calculation_version', models.CharField(max_length=64)),
                ('route', models.JSONField(default=dict)),
                ('itinerary', models.JSONField(default=list)),
                ('compliance', models.JSONField(default=dict)),
                ('logs', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
